"""
DO NOT EDIT THIS FILE DIRECTLY.
This file is auto-generated by generate_ocio_defs.py.
"""

OCIO_SPACES = [
    "Adobe RGB",
    "Display P3",
    "Linear",
    "Linear P3-D65",
    "Linear Rec.2020",
    "Linear Rec.709",
    "Log2",
    "Rec.2020",
    "Rec.709",
    "XYZ",
    "raw",
    "sRGB",
]
